### ISSUE TITLE
black screen with android 10 and FLAG_SECURE

### ISSUE THREAD

**Issue by Joseph-Nathan** [hisaichi5518/native_webview#73]
webView show as black screen with FLAG_SECURE in all device not support Chrome as Android system WebView Provider 

in android 10 ,
and Huawei modern devices ,
can you supply any code to pass this issues

**Comment by hisaichi5518** [comment]
- I couldn't reproduce it because I don't have a Huawei device.
- native_webview was created assuming you have an Android system WebView Provider
- But you can always contribute to native_webview. patches welcome! :)
